name: Env Variables Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: false
        description: select the env
      boolean:
        type: boolean
        required: true
        description: true/false
      choice:
        type: choice
        description: make your decision
        required: true
        options:
          - one
          - two
          - three
env:
  WF_ENV: avail to all jobs

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to only steps in log-env job
    steps:
      - name: Log Env Variables
        env:
          STEP_ENV: Avail to only this step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: LOG env 2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: print all vars
        run: |
          printenv