name: Env Variables Test
on: push
env:
  WF_ENV: avail to all jobs

jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log Env Variables
        run: |
          echo "WF_ENV: ${WF_ENV}"